### ISSUE TITLE
Getting error with PF2 system

### ISSUE THREAD

**Issue by Nerull91** [RaySSharma/foundry-modules#12]
Getting the fol error with the PF2 system with click on the button:
![image](https://user-images.githubusercontent.com/29990125/85056066-93a6fc00-b16c-11ea-80e0-8530e22fa55e.png)

**Comment by kryostase** [comment]
Same error here. Can you fix that please?

**Comment by RaySSharma** [comment]
Fixed by [#f71f321](https://github.com/RaySSharma/foundry-modules/commit/f71f32199b140b96a6afa506251289bb9dcbffc8)
